package com.adorehairstudio.api.config;
import com.adorehairstudio.api.model.*; import com.adorehairstudio.api.repo.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import org.springframework.security.crypto.password.PasswordEncoder; import java.math.BigDecimal; import java.util.*;
@Configuration
public class SeedData {
 @Bean CommandLineRunner seed(ProductRepository p,ServiceItemRepository s,TestimonialRepository t,SiteSettingsRepository st,AdminUserRepository a,PasswordEncoder pe,@Value("${app.admin.email}")String email,@Value("${app.admin.password}")String password){return args->{
  if(a.count()==0){AdminUser u=new AdminUser();u.setEmail(email);u.setPasswordHash(pe.encode(password));a.save(u);} if(st.count()==0){SiteSettings x=new SiteSettings();x.setPhone("+233 55 651 6470");x.setWhatsapp("233556516470");x.setEmail("maureenasumda1@gmail.com");x.setInstagram("https://instagram.com/m.nyx12/");x.setAddress("Tema - Michel Camp, Ghana");x.setHeroEyebrow("Luxury Hair • Tema");x.setHeroTitle("Wear Your Crown With Confidence");x.setHeroTagline("Luxury wigs, flawless installations and expert styling crafted for you.");st.save(x);} 
  if(p.count()==0){String[][] rows={{"Lumi Bone Straight","10 inches silky body wave pattern with beautiful natural movement.","1300","New Arrival","wig2.jpg","body-wave","1500"},{"10 Inches Bob unit","Ultra-thin 10 inches Bob unit wig creates an invisible hairline.","400","Best Seller","wig3.jpg","lace","500"},{"Curly Human Hair Wig","Luscious defined curls in 100% premium human hair.","1450","Popular","wig4.jpg","curly",""},{"Custom Colored Wig","Bold ombre and custom colour work by our expert colorists.","1850","Custom","wig5.jpg","colored","2200"},{"Straight Silk Lace Wig","Pin-straight silky texture with a natural-looking lace front.","1350","New","wig6.jpg","lace",""},{"4x4 Closure Wig","Natural scalp-like closure gives you freedom to part anywhere.","1100","","wig7.jpg","closure",""},{"Deep Wave Frontal Wig","Rich deep wave texture that holds beautifully wet or dry.","1550","Trending","wig8.jpg","body-wave",""},{"Bouncy Curls","Full, voluminous bouncy curls that celebrate natural texture.","1600","","wig9.jpg","curly",""}};int i=0;for(String[]r:rows){Product x=new Product();x.setName(r[0]);x.setDescription(r[1]);x.setPrice(new BigDecimal(r[2]));x.setTag(r[3]);x.setImageUrl(r[4]);x.setCategory(r[5]);x.setProductType("WIG");x.setStars(5);x.setActive(true);x.setDisplayOrder(i++);x.setFeatured(Set.of("Lumi Bone Straight","10 Inches Bob unit","Custom Colored Wig").contains(r[0]));if(!r[6].isBlank())x.setOldPrice(new BigDecimal(r[6]));p.save(x);}}
  if(s.count()==0){String[][] rows={{"fa-scissors","Custom Wig Making","Bespoke wigs handcrafted to your measurements, hair type, and style vision.","From GH₵ 300"},{"fa-magic","Wig Installation","Flawless wig installation with seamless blending.","From GH₵ 200"},{"fa-sync-alt","Wig Revamping","Breathe new life into your favourite wig — deep clean, reshape, colour, and restore.","From GH₵ 100"},{"fa-heart","Bridal Hair Styling","Your perfect wedding day hair, created around your bridal look.","From GH₵ 300"},{"fa-leaf","Hair Treatment","Deep conditioning, protein treatments, and scalp therapies.","From GH₵ 120"}};int i=0;for(String[]r:rows){ServiceItem x=new ServiceItem();x.setIcon(r[0]);x.setName(r[1]);x.setDescription(r[2]);x.setPriceLabel(r[3]);x.setActive(true);x.setDisplayOrder(i++);s.save(x);}}
  if(t.count()==0){String[][] rows={{"Adore Hair Studio made the most beautiful wig for me. The quality is absolutely amazing.","Abena Asante","Verified Client, Accra"},{"The wig installation was flawless! It looks so natural and the team is incredibly professional.","Efua Mensah","Loyal Client"},{"I ordered a custom-colored wig and it exceeded every expectation.","Ama Owusu","Custom Wig Client"}};int i=0;for(String[]r:rows){Testimonial x=new Testimonial();x.setText(r[0]);x.setName(r[1]);x.setTitle(r[2]);x.setStars(5);x.setActive(true);x.setDisplayOrder(i++);t.save(x);}}
 };}
}
