package com.adorehairstudio.api.controller;
import com.adorehairstudio.api.model.*; import com.adorehairstudio.api.repo.*; import jakarta.validation.Valid; import org.springframework.http.ResponseEntity; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/admin")
public class AdminController {
 private final ProductRepository p; private final ServiceItemRepository s; private final TestimonialRepository t; private final ContactMessageRepository m; private final SiteSettingsRepository st;
 public AdminController(ProductRepository p,ServiceItemRepository s,TestimonialRepository t,ContactMessageRepository m,SiteSettingsRepository st){this.p=p;this.s=s;this.t=t;this.m=m;this.st=st;}
 @GetMapping("/products") public List<Product> products(){return p.findAll();} @PostMapping("/products") public Product add(@Valid @RequestBody Product x){x.setId(null);return p.save(x);} @PutMapping("/products/{id}") public Product update(@PathVariable Long id,@Valid @RequestBody Product x){x.setId(id);return p.save(x);} @DeleteMapping("/products/{id}") public void del(@PathVariable Long id){p.deleteById(id);}
 @GetMapping("/services") public List<ServiceItem> services(){return s.findAll();} @PostMapping("/services") public ServiceItem addS(@Valid @RequestBody ServiceItem x){x.setId(null);return s.save(x);} @PutMapping("/services/{id}") public ServiceItem updateS(@PathVariable Long id,@Valid @RequestBody ServiceItem x){x.setId(id);return s.save(x);} @DeleteMapping("/services/{id}") public void delS(@PathVariable Long id){s.deleteById(id);}
 @GetMapping("/testimonials") public List<Testimonial> testimonials(){return t.findAll();} @PostMapping("/testimonials") public Testimonial addT(@Valid @RequestBody Testimonial x){x.setId(null);return t.save(x);} @PutMapping("/testimonials/{id}") public Testimonial updateT(@PathVariable Long id,@Valid @RequestBody Testimonial x){x.setId(id);return t.save(x);} @DeleteMapping("/testimonials/{id}") public void delT(@PathVariable Long id){t.deleteById(id);}
 @GetMapping("/messages") public List<ContactMessage> messages(){return m.findAll().stream().sorted(Comparator.comparing(ContactMessage::getCreatedAt).reversed()).toList();} @PutMapping("/messages/{id}/read") public ResponseEntity<?> read(@PathVariable Long id){var found=m.findById(id); if(found.isEmpty()) return ResponseEntity.notFound().build(); var x=found.get(); x.setReadMessage(true); m.save(x); return ResponseEntity.ok(x);} @DeleteMapping("/messages/{id}") public void delM(@PathVariable Long id){m.deleteById(id);}
 @GetMapping("/settings") public SiteSettings settings(){return st.findById(1L).orElseGet(SiteSettings::new);} @PutMapping("/settings") public SiteSettings settings(@RequestBody SiteSettings x){x.setId(1L);return st.save(x);}
}
